kamaradclimber/heishamon-homeassistant

custom_components/heishamon/manifest.json
Change-Id: I3ddcb30813f23bd5b67633600df2c60aee6f2d35
Reference: https://github.com/kamaradclimber/heishamon-homeassistant/actions/runs/3263354407
=> 💚 Correct manifest.json

custom_components/heishamon/__init__.py, custom_components/heishamon/binary_sensor.py, custom_components/heishamon/definitions.py, custom_components/heishamon/models.py, custom_components/heishamon/sensor.py, custom_components/heishamon/switch.py
and fetch the device model at the same time.
Change-Id: I47d146c6d2e7853a57177d4cb9334c1295c6a596
=> ✨ Group all entities behind the same device

custom_components/heishamon/definitions.py, custom_components/heishamon/sensor.py
Change-Id: I3d628da0b7caf10209c2140c0c8e9f83d2c8618f
=> 🔧 Configure some sensors as "diagnostics"

custom_components/heishamon/sensor.py
Otherwise the 3 built-in templates are free-floating
Change-Id: Idd612eaf7c63ed367ed1d53d73d772dd28825382
=> 🐛 Link built-in templates to same device

custom_components/heishamon/definitions.py, custom_components/heishamon/sensor.py
Mostly extracting sensors from the stats message
Change-Id: I2261b9725f2cec4eed002adbd0349a274a03c028
=> ✨ Add more diagnostic sensors

custom_components/aquarea/definitions.py
This will allow to start heating via HA
Change-Id: Ia41d490433a2a75fc48c057c0824cac1a8585dd3
=> ✨ Allow to set operating mode

custom_components/aquarea/__init__.py, custom_components/aquarea/definitions.py, custom_components/aquarea/number.py
Change-Id: I9b4b3ab81977133343d9a01cb646ff61013c166c
=> ✨ Allow to set target temperature for DWH

custom_components/aquarea/definitions.py
Some entities might be replaced by actuators when I'll get to this
Change-Id: I3e4c56100f12d4b393189175dd562a8c8d90ff50
=> ✨ Add entities from TOP0 to TOP57

custom_components/aquarea/definitions.py
I've skipped a few things related to heatpump generation J and Solar setups. Interested people will add them if necessary
Change-Id: If0392aac4e7b125430c1c315aaa93bf5e5252b6b
=> ✨ Add most entities to TOP101

custom_components/aquarea/definitions.py
Change-Id: I6ae9aae785bbf8aa6d1ad93f88423f34107496ab
=> ✨ Implement operations up to SET8

custom_components/aquarea/binary_sensor.py, custom_components/aquarea/definitions.py, custom_components/aquarea/number.py, custom_components/aquarea/select.py, custom_components/aquarea/sensor.py, custom_components/aquarea/switch.py
Change-Id: Iff642bc9f5d5607e32bf917fa34397bbcd200207
=> :art:  Automatically adjust shift/direct mode in UI

custom_components/aquarea/definitions.py
I've skipped the generation J specifics
Change-Id: Iba13ad57331bcc1ae60a6ddd39ceca66f1909aad
=> ✨ Implement commands up to SET24

custom_components/aquarea/definitions.py
Change-Id: I72a4c549ef2425a73d3d374c108e95df7a5f977a
=> 🐛 Correct Z2 Temp visible name

custom_components/aquarea/definitions.py, custom_components/aquarea/select.py, hacs.json
I'll revert this commit after HA 2022.11 release
Change-Id: Icee6be6a79bf51e29f49cd859f989ee5c1c3c5f5
=> ⬇ Decrease home assistant version constraint

custom_components/aquarea/definitions.py, custom_components/aquarea/select.py, hacs.json
This will allow to use recent implementation of "options" in select entities.
This reverts commit 9b6f0f3140675c2ee9c417c352b84ff5cb93d7d7.
=> ⬆ Require most recent HA version

custom_components/aquarea/sensor.py
Related to #22
Change-Id: I9e124a6283bc0ceb0c53b49a306fcf182a3f2b9d
=> ✨ Detect s0 sensors

custom_components/aquarea/sensor.py
Change-Id: I27f32c0ebc09bd90754093aec412a5fb03a993d5
=> 🐛 Correct mqtt channels for S0 sensors

custom_components/aquarea/climate.py
This change is in-line with what actual Heat Pump allows to set
=> Allow DHW minimum temperature of 40 degrees

custom_components/aquarea/climate.py
This should allow heatpump in COMPENSATION_CURVE mode to work properly
- fix 2 mqtt topic listeners
- properly write HA state when changing heating mode
- default to DIRECT mode (not super useful but it seems to be the main operating mode for heatpumps)
Relates to #34
Change-Id: I0daa5f4d36a2ab758e323aab0a6f522f492141b7
=> 🐛 Fix multiple issues around climate components

README.md, custom_components/aquarea/__init__.py, custom_components/aquarea/binary_sensor.py, custom_components/aquarea/climate.py, custom_components/aquarea/config_flow.py, custom_components/aquarea/definitions.py, custom_components/aquarea/manifest.json, custom_components/aquarea/number.py, custom_components/aquarea/select.py, custom_components/aquarea/sensor.py, custom_components/aquarea/strings.json, custom_components/aquarea/switch.py, custom_components/aquarea/translations/en.json
This patch includes a version upgrade of the config_entry format which is revertable (in theory at least)
Change-Id: Id072622306d53ad7637cec392c790dfb67b49026
=> ✨ Support any heishamon mqtt prefix

custom_components/aquarea/definitions.py
Change-Id: I2ced53562928e913045e5605b118af6afdf1c0eb
=> ✨ Add link to heishamon web interface

README.md, custom_components/aquarea/config_flow.py, custom_components/aquarea/sensor.py
By using MQTT discovery, we are able to detect multiple heatpumps and treat them as distinct artifacts
Change-Id: I5d1014aef0489d53235873d52859f79bca4d4913
=> ✨ Support multiple heatpumps

.gitignore, custom_components/aquarea/definitions.py
Fixes #53
Change-Id: Ia71029b63c905b7341304f22c4d19ea53fd2d284
Reference: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics
=> 🐛 Define state_class for each sensor

custom_components/aquarea/definitions.py
=> :pencil2:  Fix typo

custom_components/aquarea/__init__.py, custom_components/aquarea/definitions.py
This should help a bit with #57
Change-Id: I914ebc267517105e0eaffb6411a2672158a29658
=> 🔎 Add more log when ignoring value from HeishaMon

custom_components/aquarea/config_flow.py, custom_components/aquarea/strings.json, custom_components/aquarea/translations/en.json
The integration is made to be setup via auto-discovery. It led to bug when launching integration configuration manually.
Change-Id: Id20f041de789ad94bbd32b972d1f360004ef13af
=> ⛔ Forbid manual setup of integration

README.md, custom_components/aquarea/manifest.json
and moving to version 1.0.0
Change-Id: Ic56fb52f26d44de6d09c3047b966962a7bada4c5
=> 🎉 Integration if default hacs repository

custom_components/aquarea/definitions.py
wrong path assumed to set holiday mode
=> SetHolidayMode - mqtt path correction

custom_components/aquarea/definitions.py
I have added buffer tank delta reading, and set command. It is not available in current heishamon release, but will be in feature release.
=> Add buffer tank control logic

custom_components/aquarea/definitions.py
Fix #73
Thanks @Bucky2k for the report
Change-Id: I7ae47f8c07e6e127acf46e1399b528d3885e2b7b
=> 🐛 Allow to set powerful mode

custom_components/aquarea/definitions.py
We set a boolean but outcome is a 3-state system
Fix #75
Change-Id: Ie1b4d192c0640c1181c2d523098ae1e3b1d1fa18
=> 🐛 Correct holiday mode management

custom_components/aquarea/sensor.py
Fix #52
Change-Id: I19977df0cd47ee735a4940e1bf5cdf3612d3902b
=> Suppress decimals for energy readings

hacs.json
Change-Id: Ib160787dc2ad45bf38b5e410b427dbd1b9bdfa63
=> ⬆ Bump HA requirement

hacs.json
previous constraint was an error
Change-Id: I30d0ba80266e1c6f16468b7407649a674d5fc9d9
=> ⬇ Relax constraint on HA

custom_components/aquarea/definitions.py
=> 🐛 Correct pump duty running sensor

custom_components/aquarea/sensor.py, hacs.json
There was a breaking change in 2023.9
=> 🐛 Adapt to 2023.9

custom_components/aquarea/sensor.py, hacs.json
Partial revert of 3ed7acadfe1f7b076fe938c76b0b7b182c72046b
Fixes #105
=> ⬇ Restore backward compatibility

custom_components/aquarea/water_heater.py
=> ✨ Cover all temperature range

custom_components/aquarea/definitions.py
=> ✨ Support SetDemandControl command

custom_components/aquarea/definitions.py
This introduces a small breaking change by removing some existing sensor entities and replacing them with a number entity
Fix #114
=> ✨ Allow heat/cool curves manipulation

README.md
=> 🎨 Add instructions for compensation curve visualization

custom_components/aquarea/sensor.py
- fix unit
- fix significant figures
=> 🐛 Correct COP presentation

custom_components/aquarea/sensor.py
=> 🎨 Improve production/consumption entity presentation

custom_components/aquarea/definitions.py
=> 🐛 Fix topic prefix for SetDemandControl

custom_components/aquarea/update.py
This patch makes sure HA displays the update in the "Settings" view, even though we can't really update via HA at the moment.
It makes updates very visible
Slight improvement on #133
=> ✨ Pseudo update support

custom_components/aquarea/definitions.py, custom_components/aquarea/sensor.py
=> ✨ Support K & L "extra" topics

custom_components/aquarea/definitions.py, custom_components/aquarea/sensor.py
Those entities have weird behavior for K/L models: the "normal" topics send value like -200 and only the "extra" topics have valid values
Fix #141
=> 🐛 Always use first non-negative value for power entities

custom_components/aquarea/sensor.py
Topics are ordered from most specific to least specific. We take the first set of 3 topics that have at least a value.
Related to #141
=> Guess topics that are relevant for consumption/production

custom_components/aquarea/sensor.py
=> 🐛 Correct heuristic for production/consumption

custom_components/aquarea/definitions.py, custom_components/aquarea/sensor.py
Several topics have been renamed
=> ✨ Prepare firmware 3.2.3+ support

custom_components/aquarea/definitions.py
This patch adds a few sensor that were missing
=> ✨ Add missing topics

custom_components/aquarea/sensor.py
It will help to integrate with the energy dashboard (and have long term statistics)
Fix #51
=> ✨ Expose integration sensors

custom_components/aquarea/models.py
model no 28 is definitely a WH-MDC05J3E5
=> Update model desc

custom_components/aquarea/definitions.py
* Range is from 20c to 60c when using direct heating mode
* Heat_Pump_Model	5	IDU:WH-SXC12H9E8, ODU:WH-UX12HE8
=> Fix SetZ1HeatRequestTemp range when in direct mode

custom_components/aquarea/definitions.py, custom_components/aquarea/number.py
Last patches froze the entity description objects so we can't update them anymore at runtime.
Fix #174
=> 🐛 Fix update of frozen description

custom_components/aquarea/definitions.py
Add missing switch for buffer tank
=> Add buffer tank switch

custom_components/aquarea/definitions.py
Removes unsuitable device_class from
AquareaRoom Heater Enabled
Aquarea Force heater status
=> Removes unsuitable device classes

custom_components/aquarea/definitions.py
Fix setting ranges for these:
SetHeaterStopDelta
SetHeaterStartDelta
Heater_Delay_Time
Heat Outside Low, in J-series can set to -20
=> Correcting four setting ranges

custom_components/aquarea/sensor.py
All energy is taken from water temperature in defrost
Fix #181
=> Set COP to -1 when defrost mode is on

custom_components/aquarea/definitions.py
=> Consider -128 as indication a zone is OFF

custom_components/aquarea/sensor.py
=> 🐛 Correct reading of defrosting

custom_components/aquarea/definitions.py
corrected the topic name for flowrate mode
Fix #195
=> Update definitions.py correcting the Flowrate Mode Topic

custom_components/aquarea/climate.py
=> Cancel COP computation if defrost is in progress

custom_components/aquarea/update.py
=> Ignore alpha versions for heishamon update

custom_components/aquarea/definitions.py
=> Add active rules sensor

custom_components/aquarea/sensor.py
=> Add measurement state_class to 1wire sensors

custom_components/aquarea/definitions.py
=> fix min/max values for cooling curve

custom_components/aquarea/sensor.py, hacs.json
This restore compatibility after home-assistant/core#110685
Fix #222
=> ⬆️ Compatibility with HA 2024.7

custom_components/aquarea/climate.py
This may help at some point for #220
=> ⚙️ Display warning when target temperature seems out of range

custom_components/aquarea/climate.py
Without this, receiving Cooling_Mode=0 can wrongly set the heating mode in compensation mode.
Relates to #220, possibly fixing it.
=> 🐛 Distinguish between cool/heat climate mode

custom_components/aquarea/definitions.py
Fix #227 
Reference: https://github.com/IgorYbema/HeishaMon/tree/main?tab=readme-ov-file#large-board-relay-control
=> ✨ Support relay for large board control

custom_components/aquarea/climate.py, custom_components/aquarea/definitions.py
This reverts commit ebfa71d.
#220 shows the feature broke for other users. Let's revert until we find a solution.
=> ◀️ Revert cooling mode for climate  entities

custom_components/aquarea/definitions.py
This reverts commit 45587cb6830a28b7bea4bcb412812fd44f9dde00.
=> Reapply "fix min/max values for cooling curve (#219)"

custom_components/aquarea/definitions.py
=> ⚙️ Tune ranges for Z*_Cool_Request_Temp controls

custom_components/aquarea/climate.py
This adds a dedicated climate component for cooling.
It proves a bit complex to get cooling/heating working in the same
component without bug due to all different modes that exist.
Thus we introduce the cooling control as a separate climate for now.
It's supposed to be temporary.
=> ✨ Re-introduce climate support for cooling

custom_components/aquarea/definitions.py
=> Use a dictionary instead of repeating values for smart grid mode

custom_components/aquarea/climate.py
=> 💬 Improve warning

custom_components/aquarea/climate.py
=> 🐛 Correct min temp for cooling mode

custom_components/aquarea/climate.py
=> 🐛 Disable temperature set for pumps in thermostat mode

custom_components/aquarea/climate.py
This issue comes from a simple cause but a bug in HA made it look very weird.
Cause: accessing attributes before having them defined. Fix: simply define the attribute in constructor
Fix #250
=> Correct #250

custom_components/aquarea/water_heater.py
This is not visible in the UI but can be used as an action. This can be especially useful for power shedding
=> ✨ Implement on/off for water heater

custom_components/aquarea/definitions.py, custom_components/aquarea/models.py
=> Prepare compatibility with heishamon 3.9

custom_components/aquarea/definitions.py
Those topics only exists in heishamon 3.9
=> ✨ Add support for TOP129->TOP138

custom_components/aquarea/update.py
Attributes used were not the correct ones.
It also uses a hack to get the HA state up to date
=> 🐛 Fix firmware update progress bar

custom_components/aquarea/definitions.py
This removes the unneeded `/` for some command topics.
=> fix: remove  / for some command topics

custom_components/aquarea/definitions.py
Fix value topics for some bivalent entities
=> fix: bivalent entities changes

custom_components/aquarea/definitions.py
Thanks a lot for your great integration, it's awesome!
The current cooling range in "direct" mode appears to be restrictive. The WH-ADC0309J3E5 model has an actual limit of 35 degrees.
I want to set higher temperature than 25 degrees to disable cooling effectively (setup with room thermistor).
=> Increase range for guess_shift_or_direct_and_clamp_min_max_values for cooling.

custom_components/aquarea/manifest.json, custom_components/aquarea/sensor.py, hacs.json
Fix #293
Reference: https://github.com/home-assistant/core/pull/148730
=> Ensure compatibility with 2025.8
