kamaradclimber/heishamon-homeassistant

custom_components/aquarea/__init__.py, custom_components/aquarea/definitions.py, custom_components/aquarea/select.py, hacs.json
By leveraging "select" entities instead of simple sensors, we can now control options that had more than on/off state.
It includes at least QuietMode option
We now requires HA 2022.11 (unreleased at the moment) since we need https://github.com/home-assistant/core/commit/ca9bfc8b861a0987fd097ee5d807fa40427077ff
Change-Id: I89f84bee674425cdbdd6fbea7be90f737089e309
=> ✨ Allow to update some configuration

README.md, custom_components/aquarea/definitions.py
It will avoid to overload dashboards when adding the integration. Users interested in such entities can of course re-add them and their state will be preserved.
Change-Id: I07cdf63421fb794ae12d1def01448028230f3bbd
=> 🙈 Disable less common entities

custom_components/aquarea/climate.py, custom_components/aquarea/sensor.py
It will help with #22
Change-Id: I85c150f1d8a094f8d2785a1e4da809843b04565c
=> ✨ Detect sensor plugged with 1wire

custom_components/aquarea/sensor.py
We don't need to see them apart as diagnostics of the heishamon integration
Change-Id: I6a17f0b34fd377f59d05e39a1f5633c524bd7399
=> 🎨 Hide artificial "listing" sensors as diagnostics

custom_components/aquarea/climate.py
To increase throughput in oversized DHW-systems the recommendation is to use a lower temperature so there is more volume turnover. This should reduce stale water in those systems.
=> Allow DHW minimum temperature of 45 degrees

custom_components/aquarea/climate.py, custom_components/aquarea/definitions.py
This also allow to introduce better management of operating mode and zone state with nice enums.
⚠ Detection of heating mode (compensation curve or direct) does work but does not succeed to update the climate component accordingly. Default is set to direct mode at the moment.
Change-Id: I9104290bd7c81ac253170969f1d34933da3a3ebb
=> ✨ Expose climate components for zone 1 and zone 2 heating

custom_components/aquarea/manifest.json
Technically we only support a single heatpump but we expose both heishamon device and the heatpump.
Change-Id: I3b0cd8d968f5ca32e29f581519f223b652d2b919
=> ⚙ Expose app as a hub

custom_components/aquarea/config_flow.py
Before this patch, the heatpump added before 0.9.0 was "rediscovered" and led to duplication if added by mistake. Now we properly ignore it
Change-Id: I9b4db14595c41222a6a32d60ebfdb4e885bdeaad
=> 🐛 Avoid rediscovery of pre 0.9.0 pump

custom_components/aquarea/climate.py
If we write entity to HA state before having registered entities, it creates a shallow entity without unique_id.
The only reason we write to HA state is to make sure HA took into account our changes to various attributes which is not necessary at initialization time.
Change-Id: Ifce6c1d1aee3b0d6ec927950d78434191777554c
Reference: https://github.com/kamaradclimber/heishamon-homeassistant/issues/47
=> 🐛 Write HA state after initialization only

custom_components/aquarea/climate.py
Using a warning was not necessarily appropriate and scary. For users of direct compensation, we'll still have an info message. Under normal condition, we'll just have a debug message because the method is called only to make sure we normalize all attributes.
Change-Id: I65f3b7456c83b48a408fcb9a07688ca0479e2b34
Reference: https://github.com/kamaradclimber/heishamon-homeassistant/issues/47
=> 🗒 Adjust heatpump mode log severity

custom_components/aquarea/climate.py
In a previous commit (238ce9439ee97d5647da25c0dc79417b34613160) we fixed values accepted by sensors but not the one accepted for the climate component.
It's now done.
Fix #57
Fix #66
Change-Id: Ibc9ad154a60570eb1c4790f61998ce90fc8f84b8
=> 🐛 Accept wider range of value for climate component

custom_components/aquarea/definitions.py
Start/Stop is a counter (not a duration)
Fixes #78
Change-Id: I48fa83f6c89024e6b8524cb5518f42cf132fec2b
=> 🐛 Remove incorrect device class duration

custom_components/aquarea/manifest.json
Order of keys is now imposed: domain, name then alphabetical order
Change-Id: Ib67422f0c2b5d6ffadfb6171d06ea0db0cf2268b
=> 🚨 Lint json

custom_components/aquarea/sensor.py
This will fix #86 and #87
Option defined in [this
post](https://developers.home-assistant.io/blog/2023/01/25/sensor_rounding/) has been reverted and replaced by a presentation option (instead of rounding the state).
This will implement correctly #52
Change-Id: I122a0e855098e37d38f14cb02f07c3b24a201afc
=> 🐛 Suggest precision for energy sensors

custom_components/aquarea/sensor.py
=> 🐛 Correct state_class for watthour sensors

custom_components/aquarea/__init__.py, custom_components/aquarea/climate.py, custom_components/aquarea/water_heater.py
This is a breaking change: it will remove two entities:
- the climate one used to represent water heater state)
- the sensor representing the target water heater temperature (it's already exposed by the water heater entity)
Implementation is much simpler than before but also has less feature for now:
- we can't start/stop the heater
- we can't know the state of the heater (heating or not)
=> ✨ Use proper entity for water heater

custom_components/aquarea/sensor.py
We now recompute COP from mqtt message instead of doing a dance with dynamic templates.
It allows to support multiple heatpumps easily and support users who would change entity_ids.
Fix #90
=> Improve support for COP computation

custom_components/aquarea/sensor.py
Reference: https://github.com/kamaradclimber/heishamon-homeassistant/pull/118#issuecomment-1752168901
=> 🐛 Restore previous COP behavior at rest

custom_components/aquarea/definitions.py, custom_components/aquarea/number.py
This is some sort of hack to compensate for the fact we never receive a "first" value for this entity (and HA does not want to update a number with a slider when it's original value is `None`)
Fix #124
=> Allow DemandControl entity to be updated

custom_components/aquarea/number.py
We cannot set native value in entity constructor because the entity has not been added to its platform yet.
It leads to:
> Entity number.panasonic_heat_pump_main_fakedemandcontrol (<class 'custom_components.aquarea.number.HeishaMonMQTTNumber'>) does not have a platform, this may be caused by adding it manually instead of with an EntityComponent helper, please report it to the custom integration author
Solution is to set the value in the entity added to hass callback
This is a partial fix for #127
=> 🐛 Set initial state later in the process

custom_components/aquarea/number.py
In practice, it should not make any difference because we should receive an update of the corresponding sensor from heishamon. Specifically for DemandControl, we don't receive updates so we need to set this value.
=> ✨ Optimistically update number entity value before sending payload.

custom_components/aquarea/definitions.py, custom_components/aquarea/sensor.py
This patch restore compatibility with firmwares < 3.2 by listening to
new and old mqtt topics
=> ⬇️ Support firmwares < 3.2 

custom_components/aquarea/__init__.py, custom_components/aquarea/update.py
=> ✨ Expose heishamon firmware updates as an entity

custom_components/aquarea/sensor.py
It seems COP can go up to 11.56 according to #137. We should probably not ignore those values.
Fix #137
=> 🧰 Increase maximum accepted COP

custom_components/aquarea/sensor.py
This is still linked to K/L serie for which report is negative on the normal topics and must be found somewhere else.
Fix #143
=> Ignore negative values for total production/consumption

custom_components/aquarea/update.py
Before this patch, a firmware 3.3 (or any custom build) would alternate between 3.2 and the other version. It would happen because stats_firmware_contain_version would be set to true and we would receive markers of version 3.2 as well and update HA state.
Now we ignore mzarkers of 3.1/3.2 until we are sure stats topic does not contain version information
Fix #152
=> 🐛 Only react to markers of 3.1/3.2 when relevant

custom_components/aquarea/sensor.py
It suffered from the same issue than production/consumption in #149
=> 🐛 Correct cop computation for K/L and firmware 3.2+

custom_components/aquarea/definitions.py
Holiday_Mode_State topic is already reflected in the corresponding switch.
This was raised in #163 since the removed entity is a sensor marked as "config" which is now forbidden (config entities are supposed to be read-write, otherwise they should be marked as diagnostic).
Fix #163
=> 🐛 Remove duplicated entity

custom_components/aquarea/sensor.py
This is an attempt to improve situation for #168.
Before this patch, trapezoid method used to "hallucinate" energy usage: after a period of 1h at 0 W, a new value at 800W would be considered as 400Wh instead of 0.
After this patch, the same scenario should count 0Wh.
We still have an issue for cases when consumption/production does not change for a long time (and is different from 0) but it should not be a problem because heatpump usually vary in consumption/production quite often.
=> 🐛 Improve integration precision

custom_components/aquarea/definitions.py, custom_components/aquarea/update.py
https://developers.home-assistant.io/blog/2023/12/11/entity-description-changes/ introduced a breaking change earlier than the announced 2025.1.
It happens for dataclass that don't simply inherit from EntityDescription but use a mixin pattern.
In this integration, we use the HeishaMonEntityDescription dataclass as a mixin to factorize common fields that are shared by all entities (mostly linked to the fact that all entities are linked to MQTT topics and need to process incoming messages).
Apparently many custom integration are affected by this.
Fix #171
Reference: https://developers.home-assistant.io/blog/2023/12/11/entity-description-changes/
Reference: https://github.com/home-assistant/core/issues/106617#issuecomment-1871979644
Reference: …
=> 🐛 Compatibility with 2024.1

custom_components/aquarea/definitions.py, custom_components/aquarea/update.py, hacs.json
This patch introduces a backward compatible dataclass decorator that works whether core HA sets EntityDescription base dataclass as frozen or not.
This patch can be removed when we remove compatibility with HA 2023.x
This is a followup to PR #172
Fix #171
=> ⬇ Restore compatibility with HA versions before 2024.1

custom_components/aquarea/binary_sensor.py, custom_components/aquarea/number.py, custom_components/aquarea/select.py, custom_components/aquarea/sensor.py
Goal is to allow people to expose safely those entities as read-only in their dashboard.
Fix #151
=> Expose all switch as binary sensor as well

custom_components/aquarea/climate.py
Mode of operation is defined per zone based on Sensor Settings, not as currently implemented based on global Heating Mode.
=> switch to Sensor Settings for mode configuration for climate entity

custom_components/aquarea/definitions.py
Kelvin is not a unit known to HA so it create warnings
=> Correct units of solar entities

custom_components/aquarea/climate.py
This is related to #215.
Support is partial at the moment:
- we can switch off/on cooling mode
- it works for each zone
What does not work: controlling cooling temperature is not easy because of "direct" vs "compensation" modes.
=> ✨ Start support for cool mode in climate entities

custom_components/aquarea/water_heater.py
Before we received the first mqtt message about target temperature, any call to update_temperature_bounds leads to a failure.
It's better to not update the temperature bounds and wait for target_temperature_message.
Fix #234
=> 🐛 Avoid early error in water heater

custom_components/aquarea/definitions.py
With optional pcb emulation enabled, we can use smart grid mode of the heat pumps.
As this is the first time I did something with python for home assistant and only the second time I did something with python in general, I basically copied over some other entity and modified it until it worked.
The selected value is not retained in HA, only written to heishamon. So this is definitely an possible improvement to do in the future. Afaik there is no way to get the current value from heishamon (it's not even in its GUI, nor did I find something in its source code), so I guess we would have to save it in HA (or just a runtime only variable in this addon?) and hope that it's still up to date. As I don't know the best way to achieve this, I haven't bothered with it yet.
I verified this by logging …
=> Implement support for smart grid mode

custom_components/aquarea/definitions.py
The optional PCB commands `SetDemandControl` and `SetSmartGridMode` are neither written to any memory, nor are they published by heishamon to mqtt.
In order to retain the selected values in home assistant on page refresh and reboots and to reapply the values after an heishamon reset or reboot, I've set the mqtt flag `retain` to true of these commands and changed the subscribed mqtt topic to the actual command topics.
This way we have the mentioned benefits (keep values in HA, reapply values after heishamon reboot).
I couldn't think of any negative implications or reasons why we wouldn't want this behavior.
In contrast to regular (non-optional-pcb) commands like `SetQuietMode`, which are stored in the heat pump's memory, we shouldn't even have write cycles on the EEPROM as they are …
=> Retain volatile optional pcb settings

custom_components/aquarea/climate.py
Two bugs:
- range is exclusive on the upper bound
- range is a set of discrete values
=> 🐛 Correct inclusion check

custom_components/aquarea/definitions.py
Since there is no way to get the current value of demandcontrol, HA listens to the same topic where we send the command. Thus when users set DemandControl to 20%, we send "81.2" via mqtt. HA reads that value and tries to cast it to an int.
fix #252
=> Fix SetDemandControl

custom_components/aquarea/water_heater.py
https://github.com/home-assistant/core/pull/132888 broke backward compatibility.
This patch will make this integration compatible with 2025.1 and still be backward compatible with earlier version.
Relates to https://github.com/home-assistant/core/issues/133216 and https://github.com/home-assistant/core/pull/132888
Reference: https://developers.home-assistant.io/blog/2024/12/13/water-heater-entity-description/
=> 🔭 Compatibility with HA 2025.1

custom_components/aquarea/definitions.py, custom_components/aquarea/update.py
This is a nice suggestion from @IgorYbema, thanks!
Fix #248
=> ✨ Support firmware update from HA

custom_components/aquarea/definitions.py
This warning was introduced by previous release and had no effect (although the associated code upstream mentions it should be removed by 2023.6)
Fix #264
=> 🔇 Remove warning

custom_components/aquarea/definitions.py
This will help cases where heishamon < 3.9 is running
=> ✨ Improve board type detection for ESP32

custom_components/aquarea/definitions.py
Hi,
the functions to remap the demand control values were wrong, and the range was 20-100% instead of the actual 5-100%.
Old behavior:
```
>>> def write_demandcontrol(value: int) -> str:
...     return str(int(value / 100 * (234 - 43) + 43))
...     
>>> write_demandcontrol(5)
'52'
>>> write_demandcontrol(100)
'234'
```
New behavior:
```
>>> def write_demandcontrol(value: int) -> str:
...     value = (value - 5) / 95 # 5% -> 100% to 0% -> 95% for remapping
...     return str(int(value * (234 - 43) + 43))
...     
>>> write_demandcontrol(5)
'43'
>>> write_demandcontrol(100)
'234'
```
This matches the documented range: https://github.com/IgorYbema/HeishaMon/blob/main/OptionalPCB.md#set-command-byte-decrypt
Same for the read function (probably only really relevant when something external …
=> fix demand control range and remapping

custom_components/aquarea/update.py
This will restore version detection.
This is really a stupid mistake I've done in the last release 🙇
Fix #277
=> 🐛 Remove debug code

custom_components/aquarea/definitions.py
Currently, the use of an external temperature sensor is only indicated by a binary_sensor. This small pull request adds the ability to specify the use of the external sensor via a switch.
=> Add SwitchEntity to select internal or external sensor

custom_components/aquarea/definitions.py
see discussion here:
[https://github.com/kamaradclimber/heishamon-homeassistant/issues/280](url)
Add the actual switch for "External Compressor Control" The currently existing "External Compressor Control" only enables that setting being controllable but does not have any physical effect on the heat pump. Only if both are "ON", there is an action. Tested for L series but should be available also for earlier series with "optional PCB emulation" enabled.
Maybe the naming could be more desriptive... but hiding is the default so only users who really want/need it will see it.
=> Add "External Compressor Contral Switch"

custom_components/aquarea/update.py
There is no reason to put it as a warning
Fix 286
=> 🔇 Remove warning at startup

custom_components/aquarea/definitions.py
Apparently some heatpump using R290 (propane) as heat transfer fluid can go up to 70°C.
Fix #298
=> Increase maximum heating temperature
